name: Comment Commands

on:
  issue_comment:        # Handle comment commands
    types: [created]
  pull_request:         # Handle renamed PRs
    types: [edited]

jobs:
  comment-trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 16
    # - run: git fetch origin master --depth 16
    # - run: git checkout master && git log -n 16
    - name: Run command handlers
      uses: extremeheat/prismarine-repo-actions@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
