name: Comment Commands

on:
  issue_comment:        # Handle comment commands
    types: [created]
  pull_request:         # Handle renamed PRs
    types: [edited]

jobs:
  comment-trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      run: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 16
    - name: Run command handlers
      uses: extremeheat/prismarine-repo-actions@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
