name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.0.0
    - id: publish
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Create Release
      if: steps.publish.outputs.type != 'none'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "${{ steps.publish.outputs.version }}" --title "Release ${{ steps.publish.outputs.version }}" --notes "${{ steps.publish.outputs.version }}"
